name: ktflutter
description: A flutter library for lazier programmers. Functions are ported from kotlin.
version: 1.0.2
author: rarnu <rarnu1985@gmail.com>
homepage: https://github.com/codemonarch/flutter_ktport

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.rarnu.ktflutter
    pluginClass: KtflutterPlugin
